version: 0.2

phases:
  install:  # Install dependencies
    commands:
      - npm install  # Install Node.js dependencies (if applicable)
      - pip install --upgrade aws-sam-cli  # Upgrade the AWS SAM CLI

  pre_build:  # Optional: Validate template or application (if applicable)
    commands:
      - sam validate --template-file template.yaml
      # - npm test                   # Run unit tests (optional)

  build:  # Build your application
    commands:
      - sam build  # Build your application (adjust if using a different build process)

  post_build:  # Package and deploy your application
  commands:
    - >
      sam package
      --template-file packaged.yaml
      --output-template-file packaged.yaml
      --s3-bucket s3-prueba-aws
    - >
      aws cloudformation deploy
      --template-file packaged.yaml
      --stack-name stack-prueba
      --capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml  # Include the packaged template file
