version: 0.2
phases:
  install:
    commands:
      - npm install
      - pip install --upgrade aws-sam-cli
  pre_build:
    commands:
      #- npm test
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket s3-prueba-aws
  post_build:
    commands:
      - sam deploy --template-file packaged.yaml --stack-name stack-prueba --capabilities CAPABILITY_IAM
artifacts:
  files:
    - template.yaml
